require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SessionResourcesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SessionResource. As you add validations to SessionResource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SessionResourcesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all session_resources as @session_resources" do
      session_resource = SessionResource.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:session_resources)).to eq([session_resource])
    end
  end

  describe "GET #show" do
    it "assigns the requested session_resource as @session_resource" do
      session_resource = SessionResource.create! valid_attributes
      get :show, {:id => session_resource.to_param}, valid_session
      expect(assigns(:session_resource)).to eq(session_resource)
    end
  end

  describe "GET #new" do
    it "assigns a new session_resource as @session_resource" do
      get :new, {}, valid_session
      expect(assigns(:session_resource)).to be_a_new(SessionResource)
    end
  end

  describe "GET #edit" do
    it "assigns the requested session_resource as @session_resource" do
      session_resource = SessionResource.create! valid_attributes
      get :edit, {:id => session_resource.to_param}, valid_session
      expect(assigns(:session_resource)).to eq(session_resource)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SessionResource" do
        expect {
          post :create, {:session_resource => valid_attributes}, valid_session
        }.to change(SessionResource, :count).by(1)
      end

      it "assigns a newly created session_resource as @session_resource" do
        post :create, {:session_resource => valid_attributes}, valid_session
        expect(assigns(:session_resource)).to be_a(SessionResource)
        expect(assigns(:session_resource)).to be_persisted
      end

      it "redirects to the created session_resource" do
        post :create, {:session_resource => valid_attributes}, valid_session
        expect(response).to redirect_to(SessionResource.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved session_resource as @session_resource" do
        post :create, {:session_resource => invalid_attributes}, valid_session
        expect(assigns(:session_resource)).to be_a_new(SessionResource)
      end

      it "re-renders the 'new' template" do
        post :create, {:session_resource => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested session_resource" do
        session_resource = SessionResource.create! valid_attributes
        put :update, {:id => session_resource.to_param, :session_resource => new_attributes}, valid_session
        session_resource.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested session_resource as @session_resource" do
        session_resource = SessionResource.create! valid_attributes
        put :update, {:id => session_resource.to_param, :session_resource => valid_attributes}, valid_session
        expect(assigns(:session_resource)).to eq(session_resource)
      end

      it "redirects to the session_resource" do
        session_resource = SessionResource.create! valid_attributes
        put :update, {:id => session_resource.to_param, :session_resource => valid_attributes}, valid_session
        expect(response).to redirect_to(session_resource)
      end
    end

    context "with invalid params" do
      it "assigns the session_resource as @session_resource" do
        session_resource = SessionResource.create! valid_attributes
        put :update, {:id => session_resource.to_param, :session_resource => invalid_attributes}, valid_session
        expect(assigns(:session_resource)).to eq(session_resource)
      end

      it "re-renders the 'edit' template" do
        session_resource = SessionResource.create! valid_attributes
        put :update, {:id => session_resource.to_param, :session_resource => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested session_resource" do
      session_resource = SessionResource.create! valid_attributes
      expect {
        delete :destroy, {:id => session_resource.to_param}, valid_session
      }.to change(SessionResource, :count).by(-1)
    end

    it "redirects to the session_resources list" do
      session_resource = SessionResource.create! valid_attributes
      delete :destroy, {:id => session_resource.to_param}, valid_session
      expect(response).to redirect_to(session_resources_url)
    end
  end

end
